public with sharing class AccountTriggerHandler extends TriggerHandler {

    protected override void initialize(List<SObject> triggerNew, TriggerContext ctx) {
    }

    protected override List<Action> beforeInsert() {
        return new List<Action>{

        };
    }

    protected override List<Action> afterInsert() {
        return new List<Action>{

        };
    }

    protected override List<Action> beforeUpdate() {
        return new List<Action>{

        };
    }

    protected override List<Action> afterUpdate() {
        return new List<Action>{

        };
    }
}